services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://flask_user:flask_password@db/flask_db
    restart: unless-stopped
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=flask_password
      - POSTGRES_DB=flask_db
    restart: unless-stopped
    # データベース初期化用のスクリプトを追加
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask_user -d flask_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: